# Generated by Django 4.2 on 2025-09-27 09:42

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boxpacking_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField(null=True)),
                ('po_id', models.IntegerField(null=True)),
                ('style_id', models.IntegerField(null=True)),
                ('box_number', models.CharField(max_length=20, null=True, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('barcode', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=150, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'box_packing',
            },
        ),
        migrations.CreateModel(
            name='delivery_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_id', models.IntegerField(null=True)),
                ('order_number', models.CharField(max_length=20, null=True, unique=True)),
                ('order_date', models.DateTimeField(default=datetime.datetime.now)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('description', models.CharField(max_length=150, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'delivery',
            },
        ),
        migrations.CreateModel(
            name='packing_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField(null=True)),
                ('po_id', models.IntegerField(null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('description', models.CharField(max_length=150, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'packing',
            },
        ),
        migrations.CreateModel(
            name='purchaseorder_item_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_id', models.IntegerField(null=True)),
                ('size_id', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=150, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'tx_order',
            },
        ),
        migrations.CreateModel(
            name='purchaseorder_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(null=True)),
                ('fy_id', models.IntegerField(null=True)),
                ('school_id', models.IntegerField(null=True)),
                ('category_id', models.IntegerField(null=True)),
                ('style_id', models.IntegerField(null=True)),
                ('size_id', models.IntegerField(null=True)),
                ('po_number', models.CharField(max_length=20, null=True, unique=True)),
                ('po_name', models.CharField(max_length=20, null=True, unique=True)),
                ('order_number', models.CharField(max_length=20, null=True, unique=True)),
                ('po_date', models.DateTimeField(default=datetime.datetime.now)),
                ('barcode', models.CharField(max_length=255, null=True)),
                ('total_quantity', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('description', models.CharField(max_length=150, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'tm_order',
            },
        ),
    ]
