# Generated by Django 4.2 on 2025-09-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder_table',
            name='barcode',
        ),
        migrations.AddField(
            model_name='boxpacking_table',
            name='size_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='packing_table',
            name='color_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='packing_table',
            name='size_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder_item_table',
            name='barcode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder_item_table',
            name='color_id',
            field=models.IntegerField(null=True),
        ),
    ]
