# Generated by Django 4.2 on 2025-09-29 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0002_remove_purchaseorder_table_barcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxpacking_table',
            name='school_id',
        ),
    ]
