# Generated by Django 4.2 on 2025-09-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0003_remove_boxpacking_table_school_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder_item_table',
            name='serial_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
