# Generated by Django 4.2 on 2025-09-29 10:05

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0004_purchaseorder_item_table_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='boxpacking_item_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_packing_id', models.IntegerField()),
                ('po_id', models.IntegerField(null=True)),
                ('barcode', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'tx_box_packing',
            },
        ),
        migrations.RenameField(
            model_name='boxpacking_table',
            old_name='po_id',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='boxpacking_table',
            old_name='size_id',
            new_name='school_id',
        ),
        migrations.AddField(
            model_name='boxpacking_table',
            name='barcode_str',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='boxpacking_table',
            name='box_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='purchaseorder_item_table',
            name='barcode_str',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='boxpacking_table',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='boxpacking_table',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterModelTable(
            name='boxpacking_table',
            table='tm_box_packing',
        ),
    ]
