# Generated by Django 4.2 on 2025-09-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0005_boxpacking_item_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxpacking_table',
            name='po_id',
            field=models.IntegerField(null=True),
        ),
    ]
