# Generated by Django 4.2 on 2025-09-30 05:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0006_boxpacking_table_po_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_item_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.IntegerField()),
                ('box_packing_id', models.IntegerField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'delivery_item',
            },
        ),
        migrations.RenameField(
            model_name='delivery_table',
            old_name='order_number',
            new_name='delivery_number',
        ),
        migrations.RemoveField(
            model_name='delivery_table',
            name='order_date',
        ),
        migrations.AddField(
            model_name='delivery_table',
            name='category_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='delivery_table',
            name='delivery_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='delivery_table',
            name='school_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='delivery_table',
            name='style_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='delivery_table',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterModelTable(
            name='packing_table',
            table='order_entry',
        ),
    ]
