# Generated by Django 4.2 on 2025-09-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0007_delivery_item_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_item_table',
            name='barcode',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
