# Generated by Django 4.2 on 2025-09-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_table',
            name='device_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
