# Generated by Django 4.2 on 2025-09-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_session_table_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_table',
            name='fcm_token',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
