# Generated by Django 4.2 on 2025-09-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company_code', models.CharField(max_length=50)),
                ('prefix', models.CharField(max_length=50)),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=50)),
                ('gstin', models.CharField(max_length=50)),
                ('state_code', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('current_fy', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('report_email', models.CharField(max_length=50)),
                ('contact_person_name', models.CharField(max_length=50)),
                ('cp_phone', models.CharField(max_length=20)),
                ('cp_mobile', models.CharField(max_length=20)),
                ('cp_email', models.CharField(max_length=50)),
                ('enc_code', models.CharField(max_length=100)),
                ('uen_code', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=300)),
                ('logo_small', models.CharField(max_length=100)),
                ('logo_invoice', models.CharField(max_length=100)),
                ('master_id', models.IntegerField()),
                ('facebook', models.URLField(null=True)),
                ('insta', models.URLField(null=True)),
                ('linkedin', models.URLField(null=True)),
                ('twitter', models.URLField(null=True)),
                ('tax_type', models.IntegerField()),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('default_shipping_rate', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('delivery_charge', models.IntegerField()),
                ('mode', models.CharField(max_length=50)),
                ('is_active', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField()),
            ],
            options={
                'db_table': 'company',
            },
        ),
    ]
