# Generated by Django 4.2 on 2025-09-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_school_table_size_table_style_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_table',
            name='short_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
