# Generated by Django 4.2 on 2025-09-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_company_table_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_table',
            name='prefix',
        ),
    ]
