# Generated by Django 4.2 on 2025-09-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_financialyear_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_table',
            name='auth_id',
            field=models.IntegerField(null=True),
        ),
    ]
