# Generated by Django 4.2 on 2025-09-25 05:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_employee_table_auth_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='category_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('is_featured', models.IntegerField(default=0)),
                ('sort_order_no', models.IntegerField(blank=True, default=0, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default=0)),
                ('updated_by', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='color_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('is_active', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=0)),
                ('updated_by', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='tm_style_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField(null=True)),
                ('category_id', models.IntegerField(null=True)),
                ('color_ids', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('style_code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'tm_style',
            },
        ),
        migrations.CreateModel(
            name='tx_style_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_id', models.IntegerField(null=True)),
                ('size_id', models.IntegerField(null=True)),
                ('position', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'tx_style',
            },
        ),
        migrations.DeleteModel(
            name='style_table',
        ),
        migrations.AddField(
            model_name='employee_table',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='employee_table',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
