# Generated by Django 4.2 on 2025-09-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_category_table_color_table_tm_style_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color_table',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
