# Generated by Django 4.2 on 2025-09-18 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder_item_table',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder_item_table',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='purchaseorder_item_table',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder_item_table',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='purchaseorder_item_table',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='purchaseorder_item_table',
            name='updated_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder_item_table',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
