# Generated by Django 4.2 on 2025-09-25 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0002_purchaseorder_item_table_created_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='box_packing_table',
        ),
        migrations.DeleteModel(
            name='delivery_table',
        ),
        migrations.DeleteModel(
            name='packing_table',
        ),
        migrations.DeleteModel(
            name='purchaseorder_item_table',
        ),
        migrations.DeleteModel(
            name='purchaseorder_table',
        ),
    ]
